# The base definition of an application. It says what the app *is*, not where
# it runs. Where it runs is decided by groups and hosts.
apiVersion: gitops.podcd.io/v1
kind: Application
metadata:
  name: local
spec:
  image: docker.io/library/nginx@sha256:72ba65eb42c10344912a84ff42408db7d34f2feb642204570ab8fc5ffd29f1d3
  ports:
    - host: 8080
      container: 80
      hostIP: 127.0.0.1
  restartPolicy: always
  stopTimeout: 30
  healthcheck:
    retries: 30
    interval: 2s
    http:
      port: 8080
      path: /
---
apiVersion: v1
kind: Pod
metadata:
  name: local-pod
spec:
  image: docker.io/library/nginx@sha256:72ba65eb42c10344912a84ff42408db7d34f2feb642204570ab8fc5ffd29f1d3
  ports:
    - host: 8081
      container: 80
      hostIP: 127.0.0.1
  restartPolicy: always
  stopTimeout: 30
  healthcheck:
    retries: 30
    interval: 2s
    http:
      port: 8081
      path: /
