apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-dev
spec:
  provider:
    vault:
      server: http://127.0.0.1:8200
      kvVersion: 2
      auth:
        tokenSecretRef:
          name: env:VAULT_TOKEN   # resolved from agent.env, never stored in Git
